<?php

defined('ABSPATH') || exit;

/**
 * Render the Cart Recovery analytics page.
 */
function wc_ac_render_analytics_page(): void {
    if (!current_user_can('view_woocommerce_reports')) {
        wp_die(esc_html__('You do not have permission to view this report.', 'wc-abandoned-cart'));
    }

    $report = wc_ac_get_analytics_report(wc_ac_get_analytics_range_days());
    $period = $report['period'];
    $summary = $report['summary'];

    ?>

    <div class="wrap woocommerce wc-ac-analytics">
        <div class="wc-ac-analytics__page">
            <header class="wc-ac-analytics__header">
                <p class="wc-ac-analytics__intro"><?php esc_html_e('Track abandoned carts, reopened carts, recovered orders, and the revenue generated by your recovery emails.', 'wc-abandoned-cart'); ?></p>

                <nav class="wc-ac-analytics__range" aria-label="<?php esc_attr_e('Date range', 'wc-abandoned-cart'); ?>">
                    <?php

                    foreach (wc_ac_get_analytics_range_options() as $days => $label) {
                        $url = wp_nonce_url(
                            add_query_arg(
                                [
                                    'page' => 'wc-ac-cart-recovery',
                                    'range' => $days,
                                ],
                                admin_url('admin.php')
                            ),
                            'wc_ac_date_range'
                        );

                        ?>

                        <a class="<?php echo (int)$days === (int)$report['range_days'] ? 'is-active' : ''; ?>" href="<?php echo esc_url($url); ?>">
                            <?php echo esc_html($label); ?>
                        </a>

                        <?php
                    }

                    $is_custom = $report['range_days'] === 'custom';
                    $start_value = $period['start_local']->format('Y-m-d');
                    $end_value = $period['end_local']->format('Y-m-d');
                    $date_range_nonce = wp_create_nonce('wc_ac_date_range');

                    ?>

                    <span class="wc-ac-analytics__custom-range <?php echo $is_custom ? 'is-active' : ''; ?>">
                        <input
                            type="date"
                            id="wc-ac-range-start"
                            value="<?php echo esc_attr($start_value); ?>"
                            max="<?php echo esc_attr($end_value); ?>"
                            aria-label="<?php esc_attr_e('Start date', 'wc-abandoned-cart'); ?>"
                            data-base-url="<?php echo esc_attr(admin_url('admin.php?page=wc-ac-cart-recovery')); ?>"
                            data-nonce="<?php echo esc_attr($date_range_nonce); ?>"
                        />
                        <span class="wc-ac-analytics__range-separator">&ndash;</span>
                        <input
                            type="date"
                            id="wc-ac-range-end"
                            value="<?php echo esc_attr($end_value); ?>"
                            min="<?php echo esc_attr($start_value); ?>"
                            aria-label="<?php esc_attr_e('End date', 'wc-abandoned-cart'); ?>"
                        />
                    </span>
                </nav>
            </header>

            <div class="wc-ac-analytics__meta">
                <span>
                    <?php

                    echo esc_html(
                        sprintf(
                            /* translators: 1: period start date, 2: period end date */
                            __('Reporting period: %1$s to %2$s', 'wc-abandoned-cart'),
                            wp_date(get_option('date_format'), $period['start_local']->getTimestamp(), wp_timezone()),
                            wp_date(get_option('date_format'), $period['end_local']->getTimestamp(), wp_timezone())
                        )
                    );

                    ?>
                </span>
            </div>

            <section class="wc-ac-analytics__cards">
                <article class="wc-ac-analytics-card is-abandoned">
                    <span class="wc-ac-analytics-card__eyebrow"><?php esc_html_e('Selected period', 'wc-abandoned-cart'); ?></span>
                    <strong class="wc-ac-analytics-card__value"><?php echo esc_html(number_format_i18n((int)$summary['abandoned'])); ?></strong>
                    <span class="wc-ac-analytics-card__label"><?php esc_html_e('Abandoned carts', 'wc-abandoned-cart'); ?></span>
                </article>

                <article class="wc-ac-analytics-card is-reopened">
                    <span class="wc-ac-analytics-card__eyebrow"><?php esc_html_e('Selected period', 'wc-abandoned-cart'); ?></span>
                    <strong class="wc-ac-analytics-card__value"><?php echo esc_html(number_format_i18n((int)$summary['reopened'])); ?></strong>
                    <span class="wc-ac-analytics-card__label"><?php esc_html_e('Reopened from email', 'wc-abandoned-cart'); ?></span>
                </article>

                <article class="wc-ac-analytics-card is-recovered">
                    <span class="wc-ac-analytics-card__eyebrow"><?php esc_html_e('Selected period', 'wc-abandoned-cart'); ?></span>
                    <strong class="wc-ac-analytics-card__value"><?php echo esc_html(number_format_i18n((int)$summary['recovered'])); ?></strong>
                    <span class="wc-ac-analytics-card__label"><?php esc_html_e('Recovered orders', 'wc-abandoned-cart'); ?></span>
                </article>

                <article class="wc-ac-analytics-card is-rate">
                    <span class="wc-ac-analytics-card__eyebrow"><?php esc_html_e('Selected period', 'wc-abandoned-cart'); ?></span>
                    <strong class="wc-ac-analytics-card__value"><?php echo esc_html(number_format_i18n((float)$summary['recovery_rate'], 1)); ?>%</strong>
                    <span class="wc-ac-analytics-card__label"><?php esc_html_e('Recovery rate', 'wc-abandoned-cart'); ?></span>
                </article>

                <article class="wc-ac-analytics-card is-revenue">
                    <span class="wc-ac-analytics-card__eyebrow"><?php esc_html_e('Selected period', 'wc-abandoned-cart'); ?></span>
                    <strong class="wc-ac-analytics-card__value"><?php echo wp_kses_post(wc_price((float)$summary['recovered_revenue'])); ?></strong>
                    <span class="wc-ac-analytics-card__label"><?php esc_html_e('Recovered revenue', 'wc-abandoned-cart'); ?></span>
                </article>

                <article class="wc-ac-analytics-card is-recoverable">
                    <span class="wc-ac-analytics-card__eyebrow"><?php esc_html_e('Current', 'wc-abandoned-cart'); ?></span>
                    <strong class="wc-ac-analytics-card__value"><?php echo wp_kses_post(wc_price((float)$summary['recoverable_revenue'])); ?></strong>
                    <span class="wc-ac-analytics-card__label">
                        <?php

                        echo esc_html(
                            sprintf(
                                /* translators: %d: number of abandoned carts */
                                _n(
                                    'Recoverable revenue from %d cart',
                                    'Recoverable revenue from %d carts',
                                    (int)$summary['current_abandoned'],
                                    'wc-abandoned-cart'
                                ),
                                (int)$summary['current_abandoned']
                            )
                        );

                        ?>
                    </span>
                </article>
            </section>

            <section class="wc-ac-analytics__charts">
                <article class="wc-ac-analytics-chart-card">
                    <div class="wc-ac-analytics-chart-card__header">
                        <div>
                            <h2><?php esc_html_e('Abandoned vs recovered', 'wc-abandoned-cart'); ?></h2>
                            <p><?php esc_html_e('Abandoned carts are plotted by auto-cancel date and include carts whose recovery email is pending or failed. Recovered orders are plotted by order date.', 'wc-abandoned-cart'); ?></p>
                            <div class="wc-ac-analytics__legend">
                                <span class="is-abandoned"><?php esc_html_e('Abandoned carts', 'wc-abandoned-cart'); ?></span>
                                <span class="is-recovered"><?php esc_html_e('Recovered orders', 'wc-abandoned-cart'); ?></span>
                            </div>
                        </div>
                    </div>
                    <?php echo wc_ac_render_analytics_counts_chart($report['chart']); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
                </article>

                <article class="wc-ac-analytics-chart-card">
                    <div class="wc-ac-analytics-chart-card__header">
                        <div>
                            <h2><?php esc_html_e('Recovered revenue', 'wc-abandoned-cart'); ?></h2>
                            <p><?php esc_html_e('Revenue is attributed only after a recovered cart becomes an order.', 'wc-abandoned-cart'); ?></p>
                        </div>
                    </div>
                    <?php echo wc_ac_render_analytics_revenue_chart($report['chart']); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
                </article>
            </section>

            <section class="wc-ac-analytics-table-card">
                <div class="wc-ac-analytics-table-card__header">
                    <div>
                        <h2><?php esc_html_e('Recent recovered orders', 'wc-abandoned-cart'); ?></h2>
                        <p><?php esc_html_e('The latest valid orders created from a recovery email link.', 'wc-abandoned-cart'); ?></p>
                    </div>
                </div>

                <?php

                if (empty($report['recent_orders'])) {
                    ?>

                    <div class="wc-ac-analytics__empty">
                        <?php esc_html_e('No recovered orders were recorded in this period.', 'wc-abandoned-cart'); ?>
                    </div>

                    <?php
                }
                else {
                    ?>

                    <div class="wc-ac-analytics-table-card__table">
                        <table class="widefat fixed striped">
                            <thead>
                                <tr>
                                    <th><?php esc_html_e('Order', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Customer', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Status', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Total', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Date', 'wc-abandoned-cart'); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php

                                foreach ($report['recent_orders'] as $order) {
                                    ?>

                                    <tr>
                                        <td>
                                            <?php

                                            if (!empty($order['edit_url'])) {
                                                ?>

                                                <a href="<?php echo esc_url($order['edit_url']); ?>">
                                                    #<?php echo esc_html($order['order_number']); ?>
                                                </a>

                                                <?php
                                            }
                                            else {
                                                ?>

                                                #<?php echo esc_html($order['order_number']); ?>

                                                <?php
                                            }

                                            ?>
                                        </td>
                                        <td><?php echo esc_html($order['email']); ?></td>
                                        <td><?php echo esc_html($order['status']); ?></td>
                                        <td><?php echo wp_kses_post(wc_price((float)$order['total_sales'])); ?></td>
                                        <td><?php echo esc_html($order['date_created']); ?></td>
                                    </tr>

                                    <?php
                                }

                                ?>
                            </tbody>
                        </table>
                    </div>

                    <?php
                }

                ?>
            </section>

            <section class="wc-ac-analytics-table-card">
                <div class="wc-ac-analytics-table-card__header">
                    <div>
                        <h2><?php esc_html_e('Recent abandoned orders', 'wc-abandoned-cart'); ?></h2>
                        <p><?php esc_html_e('The latest abandoned carts in the selected period and where each one is in the recovery pipeline.', 'wc-abandoned-cart'); ?></p>
                    </div>
                </div>

                <?php

                if (empty($report['recent_abandoned'])) {
                    ?>

                    <div class="wc-ac-analytics__empty">
                        <?php esc_html_e('No abandoned carts were recorded in this period.', 'wc-abandoned-cart'); ?>
                    </div>

                    <?php
                }
                else {
                    ?>

                    <div class="wc-ac-analytics-table-card__table">
                        <table class="widefat fixed striped">
                            <thead>
                                <tr>
                                    <th><?php esc_html_e('Order', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Customer', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Total', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Abandoned', 'wc-abandoned-cart'); ?></th>
                                    <th><?php esc_html_e('Recovery status', 'wc-abandoned-cart'); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php

                                foreach ($report['recent_abandoned'] as $row) {
                                    $status = $row['recovery_status'];

                                    ?>

                                    <tr>
                                        <td>
                                            <?php

                                            if (!empty($row['edit_url'])) {
                                                ?>

                                                <a href="<?php echo esc_url($row['edit_url']); ?>">
                                                    #<?php echo esc_html($row['order_number']); ?>
                                                </a>

                                                <?php
                                            }
                                            else {
                                                ?>

                                                #<?php echo esc_html($row['order_number']); ?>

                                                <?php
                                            }

                                            ?>
                                        </td>
                                        <td><?php echo esc_html($row['email']); ?></td>
                                        <td><?php echo wp_kses_post(wc_price((float)$row['total'])); ?></td>
                                        <td><?php echo esc_html($row['abandoned_at']); ?></td>
                                        <td>
                                            <span class="wc-ac-status-badge is-<?php echo esc_attr($status['key']); ?>">
                                                <?php echo esc_html($status['label']); ?>
                                            </span>

                                            <?php

                                            if ($status['key'] === 'recovered' && !empty($row['recovered_order_edit_url'])) {
                                                ?>

                                                <a class="wc-ac-status-badge__link" href="<?php echo esc_url($row['recovered_order_edit_url']); ?>">
                                                    <?php

                                                    echo esc_html(
                                                        sprintf(
                                                            /* translators: %s: recovered order number */
                                                            __('Order #%s', 'wc-abandoned-cart'),
                                                            $row['recovered_order_number']
                                                        )
                                                    );

                                                    ?>
                                                </a>

                                                <?php
                                            }

                                            ?>
                                        </td>
                                    </tr>

                                    <?php
                                }

                                ?>
                            </tbody>
                        </table>
                    </div>

                    <?php
                }

                ?>
            </section>

            <p class="wc-ac-analytics__note"><?php esc_html_e('Reopened carts count abandoned carts from the selected period that were reopened from a recovery email at least once. Recovered orders count only valid orders created from a recovery link in the selected period. Recovery rate is based on carts that became abandoned in the selected period.', 'wc-abandoned-cart'); ?></p>
        </div>
    </div>

    <?php
}

/**
 * Render the abandoned vs recovered chart.
 */
function wc_ac_render_analytics_counts_chart(array $chart): string {
    if (array_sum($chart['abandoned']) === 0 && array_sum($chart['recovered']) === 0) {
        return '<div class="wc-ac-analytics__empty">' . esc_html__('No abandoned or recovered carts were recorded in this period.', 'wc-abandoned-cart') . '</div>';
    }

    return wc_ac_render_analytics_chart_svg(
        $chart['labels'],
        $chart['abandoned'],
        $chart['recovered'],
        __('Abandoned carts and recovered orders by day', 'wc-abandoned-cart'),
        'count'
    );
}

/**
 * Render the recovered revenue chart.
 */
function wc_ac_render_analytics_revenue_chart(array $chart): string {
    if ((float)array_sum($chart['revenue']) <= 0.0) {
        return '<div class="wc-ac-analytics__empty">' . esc_html__('No recovered revenue was recorded in this period.', 'wc-abandoned-cart') . '</div>';
    }

    return wc_ac_render_analytics_chart_svg(
        $chart['labels'],
        $chart['revenue'],
        [],
        __('Recovered revenue by day', 'wc-abandoned-cart'),
        'currency'
    );
}

/**
 * Render a simple SVG chart in a WooCommerce-admin-like card.
 *
 * @param array<int, string> $labels X-axis labels.
 * @param array<int, int|float> $primary Primary series.
 * @param array<int, int|float> $secondary Secondary series.
 * @param string $title Accessible title.
 * @param string $mode Chart mode.
 */
function wc_ac_render_analytics_chart_svg(array $labels, array $primary, array $secondary, string $title, string $mode): string {
    $width = 840;
    $height = 320;
    $padding_left = 56;
    $padding_right = 20;
    $padding_top = 20;
    $padding_bottom = 40;
    $plot_width = $width - $padding_left - $padding_right;
    $plot_height = $height - $padding_top - $padding_bottom;
    $point_count = count($labels);
    $step_x = $point_count > 1 ? $plot_width / ($point_count - 1) : $plot_width;
    $all_values = $secondary ? array_merge($primary, $secondary) : $primary;
    $max_value = wc_ac_get_analytics_chart_max($all_values);
    $grid_steps = 4;
    $grid_markup = '';
    $bars_markup = '';
    $line_markup = '';
    $points_markup = '';
    $label_markup = '';

    for ($step = 0; $step <= $grid_steps; ++$step) {
        $ratio = $step / $grid_steps;
        $y = $padding_top + $plot_height - ($plot_height * $ratio);
        $value = $max_value * $ratio;
        $grid_markup .= sprintf(
            '<line x1="%1$s" y1="%2$s" x2="%3$s" y2="%2$s" class="wc-ac-chart__grid-line" /><text x="%4$s" y="%5$s" class="wc-ac-chart__axis-label">%6$s</text>',
            esc_attr((string)$padding_left),
            esc_attr((string)round($y, 2)),
            esc_attr((string)($width - $padding_right)),
            esc_attr((string)($padding_left - 12)),
            esc_attr((string)($y + 4)),
            esc_html($mode === 'currency' ? wc_ac_format_compact_currency($value) : wc_ac_format_compact_number($value))
        );
    }

    $label_every = $point_count <= 14 ? 1 : ($point_count <= 45 ? 5 : 10);
    $bar_width = max(4, min(14, ($plot_width / max($point_count, 1)) * ($mode === 'currency' ? 0.7 : 0.45)));
    $line_points = [];

    foreach ($labels as $index => $label) {
        $x = $padding_left + ($step_x * $index);
        $primary_value = isset($primary[$index]) ? (float)$primary[$index] : 0.0;
        $primary_y = $padding_top + $plot_height - (($primary_value / $max_value) * $plot_height);

        if ($mode === 'currency') {
            $bars_markup .= sprintf(
                '<rect x="%1$s" y="%2$s" width="%3$s" height="%4$s" rx="0" class="wc-ac-chart__bar is-revenue" />',
                esc_attr((string)round($x - ($bar_width / 2), 2)),
                esc_attr((string)round($primary_y, 2)),
                esc_attr((string)round($bar_width, 2)),
                esc_attr((string)round(($padding_top + $plot_height) - $primary_y, 2))
            );
        }
        else {
            $bars_markup .= sprintf(
                '<rect x="%1$s" y="%2$s" width="%3$s" height="%4$s" rx="0" class="wc-ac-chart__bar is-abandoned" />',
                esc_attr((string)round($x - ($bar_width / 2), 2)),
                esc_attr((string)round($primary_y, 2)),
                esc_attr((string)round($bar_width, 2)),
                esc_attr((string)round(($padding_top + $plot_height) - $primary_y, 2))
            );
        }

        if ($mode === 'count' && isset($secondary[$index])) {
            $secondary_value = (float)$secondary[$index];
            $secondary_y = $padding_top + $plot_height - (($secondary_value / $max_value) * $plot_height);
            $line_points[] = round($x, 2) . ',' . round($secondary_y, 2);

            if ($point_count <= 31) {
                $points_markup .= sprintf(
                    '<circle cx="%1$s" cy="%2$s" r="3" class="wc-ac-chart__point" />',
                    esc_attr((string)round($x, 2)),
                    esc_attr((string)round($secondary_y, 2))
                );
            }
        }

        if (($index % $label_every) === 0 || $index === ($point_count - 1)) {
            $anchor = '';
            if ($index === 0) {
                $anchor = ' style="text-anchor:start"';
            }
            elseif ($index === $point_count - 1) {
                $anchor = ' style="text-anchor:end"';
            }
            $label_markup .= sprintf(
                '<text x="%1$s" y="%2$s" class="wc-ac-chart__axis-label is-x"%4$s>%3$s</text>',
                esc_attr((string)round($x, 2)),
                esc_attr((string)($height - 12)),
                esc_html($label),
                $anchor
            );
        }
    }

    if (!empty($line_points)) {
        $line_markup = sprintf(
            '<polyline points="%1$s" class="wc-ac-chart__line" />',
            esc_attr(implode(' ', $line_points))
        );
    }

    return sprintf(
        '<svg class="wc-ac-chart" viewBox="0 0 %1$d %2$d" role="img" aria-label="%3$s"><title>%3$s</title>%4$s%5$s%6$s%7$s%8$s</svg>',
        $width,
        $height,
        esc_attr($title),
        $grid_markup,
        $bars_markup,
        $line_markup,
        $points_markup,
        $label_markup
    );
}

/**
 * Return a rounded chart maximum.
 *
 * @param array<int, int|float> $values Series values.
 */
function wc_ac_get_analytics_chart_max(array $values): float {
    $raw_max = max(array_map('floatval', $values));

    if ($raw_max <= 0) {
        return 1.0;
    }

    $scaled = $raw_max * 1.1;
    $magnitude = 10 ** floor(log10($scaled));
    $normalized = $scaled / $magnitude;

    if ($normalized <= 1) {
        $nice = 1;
    }
    elseif ($normalized <= 2) {
        $nice = 2;
    }
    elseif ($normalized <= 5) {
        $nice = 5;
    }
    else {
        $nice = 10;
    }

    return $nice * $magnitude;
}

/**
 * Format a number for chart axis labels.
 */
function wc_ac_format_compact_number($value): string {
    $value = (float)$value;

    if ($value >= 1000) {
        return number_format_i18n($value / 1000, $value >= 10000 ? 0 : 1) . 'k';
    }

    return number_format_i18n($value, $value < 10 && floor($value) !== $value ? 1 : 0);
}

/**
 * Format a currency value for chart axis labels.
 */
function wc_ac_format_compact_currency($value): string {
    $symbol = html_entity_decode(get_woocommerce_currency_symbol(), ENT_QUOTES, get_bloginfo('charset'));

    return $symbol . wc_ac_format_compact_number($value);
}
